//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace EliteSider
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FXWS.cfcSoapBinding", Namespace="http://v1_0.WebService.fxrates.markets")]
    public class FXWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public FXWSService() {
            this.Url = "http://www.newyorkfed.org/markets/fxrates/WebService/v1_0/FXWS.cfc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://v1_0.WebService.fxrates.markets", ResponseNamespace="http://v1_0.WebService.fxrates.markets")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllLatestNoonRatesReturn")]
        public string getAllLatestNoonRates() {
            object[] results = this.Invoke("getAllLatestNoonRates", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllLatestNoonRates(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllLatestNoonRates", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAllLatestNoonRates(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://v1_0.WebService.fxrates.markets", ResponseNamespace="http://v1_0.WebService.fxrates.markets")]
        [return: System.Xml.Serialization.SoapElementAttribute("getNoonRatesReturn")]
        public string getNoonRates(string currency_code, System.DateTime date1, System.DateTime date2) {
            object[] results = this.Invoke("getNoonRates", new object[] {
                        currency_code,
                        date1,
                        date2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetNoonRates(string currency_code, System.DateTime date1, System.DateTime date2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getNoonRates", new object[] {
                        currency_code,
                        date1,
                        date2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetNoonRates(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://v1_0.WebService.fxrates.markets", ResponseNamespace="http://v1_0.WebService.fxrates.markets")]
        [return: System.Xml.Serialization.SoapElementAttribute("getAllNoonRatesReturn")]
        public string getAllNoonRates(System.DateTime date1) {
            object[] results = this.Invoke("getAllNoonRates", new object[] {
                        date1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllNoonRates(System.DateTime date1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllNoonRates", new object[] {
                        date1}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAllNoonRates(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://v1_0.WebService.fxrates.markets", ResponseNamespace="http://v1_0.WebService.fxrates.markets")]
        [return: System.Xml.Serialization.SoapElementAttribute("getLatestNoonRateReturn")]
        public string getLatestNoonRate(string currency_code) {
            object[] results = this.Invoke("getLatestNoonRate", new object[] {
                        currency_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLatestNoonRate(string currency_code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLatestNoonRate", new object[] {
                        currency_code}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetLatestNoonRate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
